/**
 * Build Script for 509 Dashboard
 * Concatenates all source files into a single consolidated .gs file
 *
 * Usage: node build.js
 */

const fs = require('fs');
const path = require('path');

const SRC_DIR = path.join(__dirname, 'src');
const DIST_DIR = path.join(__dirname, 'dist');
const OUTPUT_FILE = path.join(DIST_DIR, 'ConsolidatedDashboard.gs');

// Files in build order (constants first, then modules, main last)
const BUILD_ORDER = [
  '01_Constants.gs',
  '02_MemberManager.gs',
  '03_GrievanceManager.gs',
  '04_UIService.gs',
  '05_Integrations.gs',
  '06_Maintenance.gs',
  '07_DevTools.gs',
  '08_Code.gs',
  '09_Main.gs',
  '10_CommandCenter.gs',
  '11_SecureMemberDashboard.gs',
  '12_ChecklistManager.gs'
];

const HTML_FILES = [
  'MultiSelectDialog.html'
];

function build() {
  console.log('Building consolidated dashboard...\n');

  // Ensure dist directory exists
  if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
    console.log('Created dist/ directory');
  }

  let output = '';
  let totalLines = 0;

  // Add header
  output += `/**
 * ============================================================================
 * 509 DASHBOARD - CONSOLIDATED BUILD
 * ============================================================================
 *
 * Version: 4.2.0
 * Build Date: ${new Date().toISOString().split('T')[0]}
 *
 * This file is auto-generated from the src/ directory.
 * DO NOT EDIT THIS FILE DIRECTLY - edit the source files in src/ instead.
 *
 * Source Files:
 * ${BUILD_ORDER.map(f => ' *   - ' + f).join('\n')}
 *
 * HTML Files (embedded):
 * ${HTML_FILES.map(f => ' *   - ' + f).join('\n')}
 *
 * ============================================================================
 */

`;

  // Concatenate all .gs files
  for (const file of BUILD_ORDER) {
    const filePath = path.join(SRC_DIR, file);

    if (!fs.existsSync(filePath)) {
      console.error(`ERROR: Source file not found: ${file}`);
      process.exit(1);
    }

    const content = fs.readFileSync(filePath, 'utf8');
    const lineCount = content.split('\n').length;
    totalLines += lineCount;

    output += `// ============================================================================\n`;
    output += `// SOURCE: ${file} (${lineCount} lines)\n`;
    output += `// ============================================================================\n\n`;
    output += content;
    output += '\n\n';

    console.log(`  Added: ${file} (${lineCount} lines)`);
  }

  // Embed HTML files as template strings
  output += `// ============================================================================\n`;
  output += `// EMBEDDED HTML TEMPLATES\n`;
  output += `// ============================================================================\n\n`;

  for (const htmlFile of HTML_FILES) {
    const filePath = path.join(SRC_DIR, htmlFile);

    if (!fs.existsSync(filePath)) {
      console.warn(`WARNING: HTML file not found: ${htmlFile} - skipping`);
      continue;
    }

    const content = fs.readFileSync(filePath, 'utf8');
    const lineCount = content.split('\n').length;
    totalLines += lineCount;

    // Create a function that returns the HTML content
    const funcName = htmlFile.replace('.html', '').replace(/[^a-zA-Z0-9]/g, '_') + '_HTML';

    output += `/**\n`;
    output += ` * Embedded HTML: ${htmlFile}\n`;
    output += ` * @returns {string} HTML content\n`;
    output += ` */\n`;
    output += `function get${funcName}() {\n`;
    output += `  return \`${content.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`;\n`;
    output += `}\n\n`;

    console.log(`  Embedded: ${htmlFile} (${lineCount} lines)`);
  }

  // Write output file
  fs.writeFileSync(OUTPUT_FILE, output, 'utf8');

  console.log(`\nBuild complete!`);
  console.log(`  Output: ${OUTPUT_FILE}`);
  console.log(`  Total lines: ${totalLines}`);
  console.log(`  File size: ${(output.length / 1024).toFixed(1)} KB`);
}

// Run build
build();
