#!/usr/bin/env node

/**
 * ============================================================================
 * build.js - Dashboard Build Script
 * ============================================================================
 *
 * This script merges all modular .gs files into a single ConsolidatedDashboard.gs
 * file for deployment to Google Apps Script.
 *
 * Usage:
 *   node build.js           - Build the consolidated file
 *   node build.js --watch   - Watch for changes and rebuild automatically
 *   node build.js --clean   - Remove the dist folder
 *
 * The build order is important - files are concatenated in dependency order:
 *
 * 9-FILE MODULAR ARCHITECTURE:
 * 1. Constants.gs      - Single source of truth (IDs, sheet names, column mappings)
 * 2. MemberManager.gs  - Member directory operations, form submissions
 * 3. GrievanceManager.gs - Grievance lifecycle, deadlines, filing
 * 4. UIService.gs      - Dialogs, sidebars, Comfort View, mobile UI
 * 5. Integrations.gs   - Drive, Calendar, WebApp, external services
 * 6. Maintenance.gs    - Diagnostics, data integrity, caching, audits
 * 7. DevTools.gs       - Test data, nuke/seed, validation tests (DELETE BEFORE PROD)
 * 8. Code.gs           - Core setup, hidden sheets, formulas, dashboard creation
 * 9. Main.gs           - Entry point, onOpen, triggers (must be last)
 *
 * @fileoverview Build script for merging modular files
 * @version 2.0.0
 */

const fs = require('fs');
const path = require('path');

// Configuration
const CONFIG = {
  srcDir: './src',
  distDir: './dist',
  outputFile: 'ConsolidatedDashboard.gs',

  // Files in build order (dependency order matters!)
  // 9-FILE MODULAR ARCHITECTURE
  buildOrder: [
    'Constants.gs',       // 1. Single source of truth - must be first
    'MemberManager.gs',   // 2. Member directory operations
    'GrievanceManager.gs',// 3. Grievance lifecycle management
    'UIService.gs',       // 4. UI components, Comfort View, mobile UI
    'Integrations.gs',    // 5. Drive, Calendar, WebApp, notifications
    'Maintenance.gs',     // 6. Diagnostics, data integrity, caching
    'DevTools.gs',        // 7. Test data & nuke/seed (DELETE BEFORE PRODUCTION)
    'Code.gs',            // 8. Core setup, hidden sheets, formulas
    'Main.gs'             // 9. Entry point - must be last
  ],

  // Header to add to consolidated file
  header: `/**
 * ============================================================================
 * ConsolidatedDashboard.gs - Union Steward Dashboard
 * ============================================================================
 *
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is automatically generated by build.js from the modular source files.
 * Any changes made directly to this file will be overwritten on next build.
 *
 * 9-FILE MODULAR ARCHITECTURE:
 * - Constants.gs       : Single source of truth (IDs, column mappings, policy rules)
 * - MemberManager.gs   : Member directory operations, form submissions
 * - GrievanceManager.gs: Grievance lifecycle, deadlines, filing
 * - UIService.gs       : UI components, Comfort View, mobile UI
 * - Integrations.gs    : Drive, Calendar, WebApp, notifications
 * - Maintenance.gs     : Diagnostics, data integrity, caching, audits
 * - DevTools.gs        : Test data & nuke/seed (DELETE BEFORE PRODUCTION)
 * - Code.gs            : Core setup, hidden sheets, formulas, dashboard creation
 * - Main.gs            : Entry point and triggers
 *
 * Then run: node build.js
 *
 * Generated: {{TIMESTAMP}}
 * Version: 2.3.0
 * Architecture: 9-File Modular
 * ============================================================================
 */

`
};

/**
 * Main build function
 */
function build() {
  console.log('🔨 Building ConsolidatedDashboard.gs...\n');

  // Ensure dist directory exists
  if (!fs.existsSync(CONFIG.distDir)) {
    fs.mkdirSync(CONFIG.distDir, { recursive: true });
    console.log(`📁 Created dist directory: ${CONFIG.distDir}`);
  }

  // Read and concatenate files
  let consolidated = CONFIG.header.replace('{{TIMESTAMP}}', new Date().toISOString());
  let totalLines = 0;
  let fileCount = 0;

  for (const filename of CONFIG.buildOrder) {
    const filepath = path.join(CONFIG.srcDir, filename);

    if (!fs.existsSync(filepath)) {
      console.error(`❌ Error: File not found: ${filepath}`);
      process.exit(1);
    }

    const content = fs.readFileSync(filepath, 'utf8');
    const lineCount = content.split('\n').length;
    totalLines += lineCount;
    fileCount++;

    // Add section separator
    consolidated += `\n// ${'='.repeat(76)}\n`;
    consolidated += `// SOURCE: ${filename} (${lineCount} lines)\n`;
    consolidated += `// ${'='.repeat(76)}\n\n`;

    // Add file content
    consolidated += content;
    consolidated += '\n';

    console.log(`  ✓ ${filename.padEnd(25)} ${lineCount.toString().padStart(5)} lines`);
  }

  // Write consolidated file
  const outputPath = path.join(CONFIG.distDir, CONFIG.outputFile);
  fs.writeFileSync(outputPath, consolidated);

  console.log(`\n${'─'.repeat(50)}`);
  console.log(`📦 Total: ${fileCount} files, ${totalLines} lines`);
  console.log(`✅ Output: ${outputPath}`);
  console.log(`\n💡 Copy ${CONFIG.outputFile} to your Google Apps Script project`);
}

/**
 * Clean the dist directory
 */
function clean() {
  if (fs.existsSync(CONFIG.distDir)) {
    fs.rmSync(CONFIG.distDir, { recursive: true });
    console.log(`🧹 Cleaned: ${CONFIG.distDir}`);
  } else {
    console.log('Nothing to clean.');
  }
}

/**
 * Watch for changes and rebuild
 */
function watch() {
  console.log('👀 Watching for changes...\n');
  console.log(`   Source: ${CONFIG.srcDir}`);
  console.log(`   Output: ${path.join(CONFIG.distDir, CONFIG.outputFile)}\n`);

  // Initial build
  build();

  // Watch for changes
  fs.watch(CONFIG.srcDir, { recursive: true }, (eventType, filename) => {
    if (filename && filename.endsWith('.gs')) {
      console.log(`\n📝 Changed: ${filename}`);
      console.log('🔄 Rebuilding...\n');
      build();
    }
  });

  console.log('\nPress Ctrl+C to stop watching.\n');
}

/**
 * Generate a manifest file for clasp
 */
function generateManifest() {
  const manifest = {
    timeZone: 'America/New_York',
    dependencies: {},
    exceptionLogging: 'STACKDRIVER',
    runtimeVersion: 'V8',
    oauthScopes: [
      'https://www.googleapis.com/auth/spreadsheets.currentonly',
      'https://www.googleapis.com/auth/script.container.ui',
      'https://www.googleapis.com/auth/drive',
      'https://www.googleapis.com/auth/calendar',
      'https://www.googleapis.com/auth/gmail.send',
      'https://www.googleapis.com/auth/script.scriptapp'
    ]
  };

  const outputPath = path.join(CONFIG.distDir, 'appsscript.json');
  fs.writeFileSync(outputPath, JSON.stringify(manifest, null, 2));
  console.log(`📄 Generated: ${outputPath}`);
}

/**
 * Display usage information
 */
function showHelp() {
  console.log(`
Union Steward Dashboard - Build Script

Usage:
  node build.js [command]

Commands:
  (none)     Build the consolidated file
  --watch    Watch for changes and rebuild automatically
  --clean    Remove the dist folder
  --manifest Generate appsscript.json manifest
  --help     Show this help message

Examples:
  node build.js           # Build once
  node build.js --watch   # Watch mode for development
  node build.js --clean   # Clean build artifacts
`);
}

// Parse command line arguments
const args = process.argv.slice(2);

if (args.includes('--help') || args.includes('-h')) {
  showHelp();
} else if (args.includes('--clean')) {
  clean();
} else if (args.includes('--watch') || args.includes('-w')) {
  watch();
} else if (args.includes('--manifest')) {
  if (!fs.existsSync(CONFIG.distDir)) {
    fs.mkdirSync(CONFIG.distDir, { recursive: true });
  }
  generateManifest();
} else {
  build();
}
