/**
 * ESLint Flat Configuration for Google Apps Script
 *
 * This configuration is compatible with ESLint 9.x flat config format.
 * It's set to be lenient for the existing codebase while catching critical issues.
 *
 * @see https://eslint.org/docs/latest/use/configure/migration-guide
 */

module.exports = [
  {
    // Apply to all .gs files
    files: ['src/**/*.gs'],

    languageOptions: {
      ecmaVersion: 2020,
      sourceType: 'script',
      globals: {
        // Google Apps Script globals
        SpreadsheetApp: 'readonly',
        DriveApp: 'readonly',
        GmailApp: 'readonly',
        CalendarApp: 'readonly',
        DocumentApp: 'readonly',
        FormApp: 'readonly',
        SlidesApp: 'readonly',
        Logger: 'readonly',
        Utilities: 'readonly',
        UrlFetchApp: 'readonly',
        HtmlService: 'readonly',
        PropertiesService: 'readonly',
        CacheService: 'readonly',
        LockService: 'readonly',
        ScriptApp: 'readonly',
        Session: 'readonly',
        Browser: 'readonly',
        ContentService: 'readonly',
        MailApp: 'readonly',
        Maps: 'readonly',
        Jdbc: 'readonly',
        XmlService: 'readonly',
        console: 'readonly',

        // Project-specific globals (constants defined in 01_Core.gs)
        SHEETS: 'readonly',
        COLORS: 'readonly',
        ICONS: 'readonly',
        MEMBER_COLS: 'readonly',
        MEMBER_COLUMNS: 'readonly',
        GRIEVANCE_COLS: 'readonly',
        GRIEVANCE_COLUMNS: 'readonly',
        CONFIG_COLS: 'readonly',
        COMMAND_CONFIG: 'readonly',
        ERROR_LEVEL: 'readonly',
        ERROR_CONFIG: 'readonly',
        API_VERSION: 'readonly',
        TIME_CONSTANTS: 'readonly',
        ACCESS_CONTROL: 'readonly',

        // Data Access Layer
        DataAccess: 'readonly',

        // Security functions (00_Security.gs)
        escapeHtml: 'readonly',
        sanitizeObjectForHtml: 'readonly',
        escapeForFormula: 'readonly',
        escapeForFormulaPreserveNewlines: 'readonly',
        safeSheetNameForFormula: 'readonly',
        buildSafeQuery: 'readonly',
        checkWebAppAuthorization: 'readonly',
        validateWebAppRequest: 'readonly',
        getAccessDeniedPage: 'readonly',
        maskEmail: 'readonly',
        maskPhone: 'readonly',
        maskName: 'readonly',
        maskMemberForLog: 'readonly',
        maskGrievanceForLog: 'readonly',
        secureLog: 'readonly',
        isValidSafeString: 'readonly',
        isValidMemberId: 'readonly',
        isValidGrievanceId: 'readonly',

        // Error handling (01_Core.gs)
        handleError: 'readonly',
        withErrorHandling: 'readonly',
        successResponse: 'readonly',
        errorResponse: 'readonly',
        log_: 'readonly',
        col_: 'readonly',
        setCol_: 'readonly',
        isTruthyValue: 'readonly',
        PerformanceTimer: 'readonly',
        sanitizeForQuery: 'readonly',

        // Core constants (01_Core.gs)
        GRIEVANCE_STATUS: 'readonly',
        GRIEVANCE_CLOSED_STATUSES: 'readonly',
        GRIEVANCE_STATUS_PRIORITY: 'readonly',
        GRIEVANCE_OUTCOMES: 'readonly',
        GRIEVANCE_FORM_CONFIG: 'readonly',
        DEADLINE_DEFAULTS: 'readonly',
        BATCH_LIMITS: 'readonly',
        CACHE_CONFIG: 'readonly',
        CACHE_KEYS: 'readonly',
        CALENDAR_CONFIG: 'readonly',
        DRIVE_CONFIG: 'readonly',
        DIALOG_SIZES: 'readonly',
        DROPDOWN_MAP: 'readonly',
        DEFAULT_CONFIG: 'readonly',
        HIDDEN_SHEETS: 'readonly',
        MOBILE_CONFIG: 'readonly',
        PIN_CONFIG: 'readonly',
        DASHBOARD_LAYOUT: 'readonly',
        SHEET_COLORS: 'readonly',
        SHEET_LEGACY_NAMES_: 'readonly',
        THEME_PRESETS: 'readonly',
        UI_THEME: 'readonly',
        VERSION: 'readonly',
        VERSION_HISTORY: 'readonly',
        VERSION_INFO: 'readonly',
        SECURITY_SEVERITY: 'readonly',
        SCALE_THRESHOLDS: 'readonly',
        IS_DEV_ENVIRONMENT: 'readonly',

        // Header maps (01_Core.gs)
        MEMBER_HEADER_MAP_: 'readonly',
        CONFIG_HEADER_MAP_: 'readonly',
        AUDIT_LOG_HEADER_MAP_: 'readonly',
        CHECKLIST_HEADER_MAP_: 'readonly',
        KNOWLEDGE_HEADER_MAP_: 'readonly',
        NMC_HEADER_MAP_: 'readonly',
        NOTIFICATIONS_HEADER_MAP_: 'readonly',
        RESOURCES_HEADER_MAP_: 'readonly',
        RESOURCE_CONFIG_HEADER_MAP_: 'readonly',
        SATISFACTION_HEADER_MAP_: 'writable',
        STEWARD_PERF_HEADER_MAP_: 'readonly',
        SURVEY_TRACKING_HEADER_MAP_: 'readonly',
        SURVEY_VAULT_HEADER_MAP_: 'readonly',
        MEETING_CHECKIN_HEADER_MAP_: 'readonly',

        // Column constants (01_Core.gs + various)
        AUDIT_LOG_COLS: 'readonly',
        CHECKLIST_COLS: 'readonly',
        KNOWLEDGE_COLS: 'readonly',
        NMC_COLS: 'readonly',
        NOTIFICATIONS_COLS: 'readonly',
        RESOURCES_COLS: 'readonly',
        RESOURCE_CONFIG_COLS: 'readonly',
        SATISFACTION_COLS: 'readonly',
        STEWARD_PERF_COLS: 'readonly',
        SURVEY_PERIODS_COLS: 'readonly',
        SURVEY_QUESTIONS_COLS: 'readonly',
        SURVEY_TRACKING_COLS: 'readonly',
        SURVEY_VAULT_COLS: 'readonly',
        MEETING_CHECKIN_COLS: 'readonly',
        MEMBER_PIN_COLS: 'readonly',
        MULTI_SELECT_COLS: 'readonly',
        PII_MEMBER_COLS: 'readonly',
        EVENT_AUDIT_COLS: 'readonly',
        CHECKLIST_SHEET_NAME: 'readonly',
        CHECKLIST_CATEGORIES: 'readonly',
        CHECKLIST_TEMPLATES: 'readonly',

        // Portal columns (23_PortalSheets.gs)
        PORTAL_EVENT_COLS: 'readonly',
        PORTAL_GRIEVANCE_COLS: 'readonly',
        PORTAL_MEGA_SURVEY_COLS: 'readonly',
        PORTAL_MEMBER_DIR_COLS: 'readonly',
        PORTAL_MINUTES_COLS: 'readonly',
        PORTAL_STEWARD_LOG_COLS: 'readonly',
        MINUTES_LIMITS: 'readonly',

        // Satisfaction / survey constants
        SATISFACTION_FORM_CONFIG: 'readonly',
        SATISFACTION_PREFIX: 'readonly',
        SATISFACTION_SECTIONS: 'readonly',
        SURVEY_PERIODS_COLS: 'readonly',
        ACTION_TYPE_CONFIG: 'readonly',
        MEETING_STATUS: 'readonly',
        RSVP_STATUS: 'readonly',
        TAB_MODAL_REGISTRY: 'readonly',

        // Service modules (IIFEs)
        DataService: 'readonly',
        ConfigReader: 'readonly',
        Auth: 'readonly',
        EventBus: 'readonly',
        DigestService: 'readonly',
        EngagementService: 'readonly',
        FailsafeService: 'readonly',
        MentorshipService: 'readonly',
        QAForum: 'readonly',
        RSVPService: 'readonly',
        TimelineService: 'readonly',
        TwoFactorService: 'readonly',
        WeeklyQuestions: 'readonly',
        WorkloadService: 'readonly',
        WorkloadPortal: 'readonly',
        TestRunner: 'readonly',
        Charts: 'readonly',

        // GAS advanced services
        Drive: 'readonly',
        Sheets: 'readonly',
        MimeType: 'readonly',

        // Cross-file functions (00_Security.gs)
        getUserRole_: 'readonly',
        recordSecurityEvent: 'readonly',
        safeSendEmail_: 'readonly',
        safeSendEmail: 'readonly',
        queueSecurityDigestEvent_: 'readonly',
        sendSecurityAlertEmail_: 'readonly',
        sendDailySecurityDigest: 'readonly',
        _getRateCount: 'readonly',
        _setRateCount: 'readonly',
        _clearRateCount: 'readonly',

        // Cross-file functions (00_DataAccess.gs)
        logError_: 'readonly',

        // Cross-file functions (01_Core.gs)
        getConfigValue_: 'readonly',
        getConfigValues: 'readonly',
        validateConfigValue_: 'readonly',
        warnInvalidConfigValue_: 'readonly',
        getHeadersFromMap_: 'readonly',
        getColumnLetter: 'readonly',
        getOrCreateSheet: 'readonly',
        ensureMinimumColumns: 'readonly',
        loadCachedColumnMaps_: 'readonly',
        syncColumnMaps: 'readonly',
        resolveColumnsFromSheet_: 'readonly',
        resolveColumnByHeader_: 'readonly',
        resolveColumnsByHeader_: 'readonly',
        showToast: 'readonly',
        showAlert: 'readonly',
        withScriptLock_: 'readonly',
        navigateToSheet: 'readonly',
        executeWithRetry: 'readonly',
        logAuditEvent: 'readonly',
        AUDIT_EVENTS: 'readonly',
        isProductionMode: 'readonly',
        warmUpCaches: 'readonly',
        getSystemName_: 'readonly',
        _systemNameCache_: 'writable',
        getDriveRootFolderName_: 'readonly',
        getOrgNameFromConfig_: 'readonly',
        getLocalNumberFromConfig_: 'readonly',
        getFormUrlFromConfig: 'readonly',
        fmtDateShort_: 'readonly',
        numericField_: 'readonly',
        hashEmail_: 'readonly',
        hashForVault_: 'readonly',
        addBusinessDays: 'readonly',
        addCalendarDays: 'readonly',
        generateNameBasedId: 'readonly',
        isMemberId_: 'readonly',
        isGrievanceId_: 'readonly',
        emitEditEvent: 'readonly',
        populateConfigFromSheetData: 'readonly',
        seedConfigData: 'readonly',
        restoreConfigAndDropdowns: 'readonly',
        restoreConfigFromSheetData_: 'readonly',
        _sanitizeConfig: 'readonly',

        // Cross-file functions (02_DataManagers.gs)
        MEMBER_FIELD_MAP: 'readonly',
        applyFieldUpdates_: 'readonly',
        addMember: 'readonly',
        getMemberList: 'readonly',
        getMemberById: 'readonly',
        getMemberDataById_: 'readonly',
        getMemberHeaders: 'readonly',
        getOpenGrievances: 'readonly',
        getGrievanceById: 'readonly',
        getGrievanceHeaders: 'readonly',
        getNMCHeaders: 'readonly',
        getNextGrievanceId: 'readonly',
        initiateGrievance: 'readonly',
        handleMemberEdit: 'readonly',
        handleGrievanceEdit: 'readonly',
        loadMemberData_: 'readonly',
        getSelectedGrievanceRows: 'readonly',
        createGrievancePDF: 'readonly',
        createGrievanceSnapshot: 'readonly',
        refreshAllFormulas: 'readonly',
        refreshAllHiddenFormulas: 'readonly',
        refreshMemberDirectoryFormulas: 'readonly',
        syncGrievanceToMemberDirectory: 'readonly',
        syncMemberToGrievanceLog: 'readonly',
        syncGrievanceFormulasToLog: 'readonly',
        repairGrievanceCheckboxes: 'readonly',
        repairMemberCheckboxes: 'readonly',
        sortGrievanceLogByStatus: 'readonly',
        archiveClosedGrievances: 'readonly',
        archiveOldAuditLogs_: 'readonly',
        generateMissingMemberIDs: 'readonly',
        exportUndoHistoryToSheet: 'readonly',
        getUndoHistory: 'readonly',
        undoToIndex: 'readonly',
        composeEmailForMember: 'readonly',
        emailContactFormToMember: 'readonly',
        emailDashboardLinkToMember: 'readonly',
        emailGrievanceStatusToMember: 'readonly',
        emailExecutivePDF: 'readonly',
        sendQuickEmail: 'readonly',
        bulkEmailGrievanceMembers: 'readonly',
        emailMeetingAttendanceReport: 'readonly',
        runBulkValidation: 'readonly',
        checkDataQuality: 'readonly',
        getUnifiedDashboardData: 'readonly',
        getUnifiedDashboardDataWithDateRange: 'readonly',
        getUpcomingDeadlines: 'readonly',
        getDeadlineCalendarData: 'readonly',
        getMobileDashboardStats: 'readonly',
        getMobileSearchData: 'readonly',
        getWebAppSearchResults: 'readonly',
        sendDeadlineReminders: 'readonly',
        getGrievanceFormOptions: 'readonly',
        buildGrievanceFormUrl_: 'readonly',
        getGrievanceForSigning: 'readonly',
        submitGrievanceSignature: 'readonly',
        applyAutoStyleToRow_: 'readonly',
        applyTabColors_: 'readonly',
        applyWinRateGradients: 'readonly',
        openGrievanceFormForRow_: 'readonly',
        _refreshNavBadges: 'readonly',

        // Cross-file functions (03_UIComponents.gs)
        showDialog_: 'readonly',

        // Cross-file functions (03_UIFormatting.gs / 04_UIMenus.gs / UI)
        createDashboardMenu: 'readonly',
        buildDevMenu: 'readonly',
        CREATE_DASHBOARD: 'readonly',
        getSettings: 'readonly',
        saveVisualSetting: 'readonly',
        getUserColorTheme: 'readonly',
        getColorThemeList: 'readonly',
        showThemePresetPicker: 'readonly',
        getComfortViewSettings: 'readonly',
        getCommonStyles: 'readonly',
        getMobileOptimizedHead: 'readonly',
        getClientSideEscapeHtml: 'readonly',

        // Cross-file functions (04e_PublicDashboard.gs)
        refreshMemberView: 'readonly',

        // Cross-file functions (05_Integrations.gs)
        setupDriveFolderForGrievance: 'readonly',
        autoCreateMissingGrievanceFolders_: 'readonly',
        setupDashboardCalendar: 'readonly',
        setupDashboardDriveFolders: 'readonly',
        syncDeadlinesToCalendar: 'readonly',
        syncSingleGrievanceToCalendar: 'readonly',
        calculateInitialDeadlines: 'readonly',
        calculateResponseDeadline: 'readonly',
        getDeadlineRules: 'readonly',
        SETUP_CALENDAR: 'readonly',
        SETUP_DRIVE_FOLDERS: 'readonly',
        _getOrCreateBackupFolder: 'readonly',
        getOrCreateMemberAdminFolder: 'readonly',
        sanitizeFolderName: 'readonly',

        // Cross-file functions (06_Setup.gs)
        createConfigSheet: 'readonly',
        createMemberDirectory: 'readonly',
        createGrievanceLog: 'readonly',
        createNotificationsSheet: 'readonly',
        createResourcesSheet: 'readonly',
        createKnowledgeEngineSheet: 'readonly',
        createResourceConfigSheet: 'readonly',
        createSatisfactionSheet: 'readonly',
        createSurveyQuestionsSheet: 'readonly',
        createVolunteerHoursSheet: 'readonly',
        createMeetingAttendanceSheet: 'readonly',
        createMeetingCheckInLogSheet: 'readonly',
        createConfigGuideSheet: 'readonly',
        createFAQSheet: 'readonly',
        createGettingStartedSheet: 'readonly',
        createFeaturesReferenceSheet: 'readonly',
        initializeDashboard: 'readonly',
        setupDataValidations: 'readonly',
        setupAllHiddenSheets: 'readonly',
        setupHiddenSheets: 'readonly',
        reorderSheetsToStandard: 'readonly',
        enforceHiddenSheets: 'readonly',
        setSheetVeryHidden_: 'readonly',
        setSheetVisible_: 'readonly',
        ensureAllSheetColumns_: 'readonly',
        _ensureAllSheetsInternal: 'readonly',
        migrateSheetTabTitles_: 'readonly',
        setupActionTypeColumn: 'readonly',
        setupAuditLogSheet: 'readonly',
        setupMemberLookupSheet: 'readonly',
        setupGrievanceCalcSheet: 'readonly',
        setupCalcDeadlinesSheet: 'readonly',
        setupCalcFormulasSheet: 'readonly',
        setupCalcGrievancesSheet: 'readonly',
        setupCalcMembersSheet: 'readonly',
        setupCalcStatsSheet: 'readonly',
        setupCalcSyncSheet: 'readonly',
        setupChecklistCalcSheet: 'readonly',
        setupStewardContactCalcSheet: 'readonly',
        setupStewardPerformanceCalcSheet: 'readonly',
        setupMeetingCheckInSheet: 'readonly',
        _ensureContactLogSheet: 'readonly',
        _ensureGrievanceFeedbackSheet: 'readonly',
        _ensureStewardTasksSheet: 'readonly',
        ensureGrievanceArchiveSheet_: 'readonly',
        ensureNonMemberContactsSheet_: 'readonly',

        // Triggers / sync
        createAutomationTriggers: 'readonly',
        setupMidnightTrigger: 'readonly',
        setupOpenDeferredTrigger: 'readonly',
        setupQuarterlyTrigger: 'readonly',
        setupWeeklyReminderTrigger: 'readonly',
        setupWeeklySnapshotTrigger: 'readonly',
        setupCommunityPollTrigger: 'readonly',
        installAutoSyncTrigger: 'readonly',
        installAutoSyncTriggerQuick: 'readonly',
        installHiddenSheetEnforcerTrigger: 'readonly',
        onEditAudit: 'readonly',
        onEditAutoSync: 'readonly',
        onEditMultiSelect: 'readonly',
        onSelectionChangeMultiSelect: 'readonly',
        openCellMultiSelectEditor: 'readonly',
        syncAllData: 'readonly',
        syncDashboardCalcValues: 'readonly',
        syncDashboardValues: 'readonly',
        syncGrievanceCalcSheet: 'readonly',
        syncStewardPerformanceValues: 'readonly',
        syncSatisfactionValues: 'readonly',
        syncSatisfactionSheetColumns_: 'readonly',
        syncVolunteerHoursToMemberDirectory: 'readonly',
        syncMeetingAttendanceToMemberDirectory: 'readonly',
        syncChecklistCalcToGrievanceLog: 'readonly',
        syncConfigToSheetValidation_: 'readonly',
        syncDropdownToConfig_: 'readonly',

        // Config / dropdowns
        addToConfigDropdown_: 'readonly',
        removeFromConfigDropdown_: 'readonly',
        setDropdownValidation: 'readonly',
        setMultiSelectValidation: 'readonly',
        getMultiSelectConfig: 'readonly',
        showMultiSelectDialog: 'readonly',
        buildMultiSelectCols_: 'readonly',
        buildSatisfactionColsShim_: 'readonly',
        getSatisfactionColMap_: 'readonly',
        getSatisfactionSummary: 'readonly',

        // Tab modal functions
        showTabModalConfig: 'readonly',
        showTabModalMemberDirectory: 'readonly',
        showTabModalGrievanceLog: 'readonly',
        showTabModalMeetingAttendance: 'readonly',
        showTabModalMeetingCheckIn: 'readonly',
        showTabModalResources: 'readonly',
        showTabModalVolunteerHours: 'readonly',
        showTabModalCaseChecklist: 'readonly',
        isTabModalDismissed_: 'readonly',
        isTabModalsEnabled_: 'readonly',

        // Quick action menus
        showGrievanceQuickActions: 'readonly',
        showMemberQuickActions: 'readonly',

        // Notification / messaging
        createNotification: 'readonly',
        pushNotification: 'readonly',
        sendWebAppNotification: 'readonly',
        getWebAppNotificationCount: 'readonly',
        processMeetingDocNotifications: 'readonly',
        emailSurveyToMember: 'readonly',

        // Web dashboard / auth
        diagnoseWebApp: 'readonly',
        getWebAppUrl: 'readonly',
        updateMemberProfile: 'readonly',
        findUserByEmail: 'readonly',
        _resolveCallerEmail: 'readonly',
        _requireStewardAuth: 'readonly',
        _adminIsAuthorized_: 'readonly',
        _isGrievancesEnabled: 'readonly',
        checkPINLockout: 'readonly',
        clearPINAttempts: 'readonly',
        recordFailedPINAttempt: 'readonly',
        verifyPIN: 'readonly',
        authCleanupExpiredTokens: 'readonly',
        verifyAuditLogIntegrity: 'readonly',
        verifySurveyVaultIntegrity: 'readonly',
        maskObjectPII_: 'readonly',
        getOrgChartHtml: 'readonly',
        getPOMSReferenceHtml: 'readonly',

        // Portal / sheets
        initPortalSheets: 'readonly',
        saveFormUrlsToConfig_silent: 'readonly',

        // Survey engine
        initSurveyEngine: 'readonly',
        setupSurveyPeriodsSheet: 'readonly',
        setupSurveyTrackingSheet: 'readonly',
        setupSurveyVaultSheet: 'readonly',
        startNewSurveyRound: 'readonly',
        populateSurveyTrackingFromMembers: 'readonly',
        getSurveyPeriod: 'readonly',
        getSurveyQuestions: 'readonly',
        submitSurveyResponse: 'readonly',
        sendSurveyCompletionReminders: 'readonly',
        menuInstallSurveyTriggers: 'readonly',
        getVaultDataFull_: 'readonly',
        getVaultDataMap_: 'readonly',
        incrementPeriodResponseCount_: 'readonly',

        // Meeting / event functions
        createMeetingDocs: 'readonly',
        createMeetingCalendarEvent: 'readonly',
        cleanupExpiredMeetings: 'readonly',
        updateMeetingStatuses: 'readonly',
        getMeetingAttendees: 'readonly',
        _getActiveMeetingForCheckIn: 'readonly',
        webCheckInMember: 'readonly',
        getCheckInEligibleMeetings: 'readonly',

        // Checklist functions
        createChecklistFromTemplate: 'readonly',
        getChecklistTemplate: 'readonly',
        getOrCreateChecklistSheet: 'readonly',
        handleChecklistEdit: 'readonly',

        // Steward performance / config
        handleConfigStewardEdit_: 'readonly',
        handleStageGateWorkflow_: 'readonly',
        getCorrelationAlerts: 'readonly',
        getCorrelationSummary: 'readonly',

        // Failsafe / backup
        fsBackupCriticalSheets: 'readonly',

        // Weekly questions
        wqGetActiveQuestions: 'readonly',
        wqInitSheets: 'readonly',

        // Timeline
        tlAddTimelineEvent: 'readonly',

        // Workload
        setupWorkloadReminderSystem: 'readonly',
        initWorkloadTrackerSheets: 'readonly',
        getWorkloadHistorySSO: 'readonly',

        // Data wrappers (21d_WebDashDataWrappers.gs)
        dataGetBatchData: 'readonly',
        dataGetMemberContactHistory: 'readonly',
        dataGetStewardContactLog: 'readonly',
        dataSendBroadcast: 'readonly',
        dataSendDirectMessage: 'readonly',

        // Digest / triggers
        triggerDailyTrendDetection: 'readonly',

        // QA Forum
        qaGetFlaggedContent: 'readonly',

        // Event bus
        registerEventBusSubscribers: 'readonly',

        // Contact log
        CONTACT_SHEET_TAB_: 'readonly',

        // Test runner (30_TestRunner.gs)
        // All test_* functions are defined globally for the in-GAS test runner
        test_configrd_configHasAuthFields: 'readonly',
        test_configrd_configHasDriveFields: 'readonly',
        test_configrd_configHasRequiredFields: 'readonly',
        test_configrd_getConfigCallable: 'readonly',
        test_configrd_getConfigJSONCallable: 'readonly',
        test_configrd_getConfigJSONReturnsString: 'readonly',
        test_configrd_moduleExists: 'readonly',
        test_configrd_refreshConfigCallable: 'readonly',
        test_configrd_validateConfigCallable: 'readonly',
        test_configrd_validateConfigReturnsShape: 'readonly',
        test_endpoints_adminStatsFnsExist: 'readonly',
        test_endpoints_allWriteEndpointsRejectNull: 'readonly',
        test_endpoints_batchDiagnosticFnsExist: 'readonly',
        test_endpoints_checklistFnsExist: 'readonly',
        test_endpoints_contactNotificationFnsExist: 'readonly',
        test_endpoints_coreGrievanceFnsExist: 'readonly',
        test_endpoints_grievanceDraftFnsExist: 'readonly',
        test_endpoints_meetingFnsExist: 'readonly',
        test_endpoints_notificationCountExists: 'readonly',
        test_endpoints_pollStubsRemoved: 'readonly',
        test_endpoints_surveyFeedbackFnsExist: 'readonly',
        test_endpoints_taskFnsExist: 'readonly',
        test_endpoints_thisBindingCanary: 'readonly',
        test_failsafe_diagnosticExists: 'readonly',
        test_failsafe_digestConfigReturnsShape: 'readonly',
        test_failsafe_ensureAllSheetsExists: 'readonly',
        test_failsafe_globalWrappersExist: 'readonly',
        test_failsafe_moduleExists: 'readonly',
        test_failsafe_publicAPIComplete: 'readonly',
        test_failsafe_wrappersRejectNullToken: 'readonly',
        test_portal_allCols0Indexed: 'readonly',
        test_portal_eventColsDefined: 'readonly',
        test_portal_grievanceColsDefined: 'readonly',
        test_portal_megaSurveyColsDefined: 'readonly',
        test_portal_memberDirColsDefined: 'readonly',
        test_portal_minutesColsDefined: 'readonly',
        test_portal_noDuplicateIndices: 'readonly',
        test_portal_setupFunctionsExist: 'readonly',
        test_portal_stewardLogColsDefined: 'readonly',
        test_qaforum_getQuestionsReturnsArray: 'readonly',
        test_qaforum_globalWrappersExist: 'readonly',
        test_qaforum_moduleExists: 'readonly',
        test_qaforum_paginationDefaults: 'readonly',
        test_qaforum_publicAPIComplete: 'readonly',
        test_qaforum_wrappersRejectNullToken: 'readonly',
        test_timeline_categoriesValidated: 'readonly',
        test_timeline_getEventsReturnsArray: 'readonly',
        test_timeline_globalWrappersExist: 'readonly',
        test_timeline_moduleExists: 'readonly',
        test_timeline_publicAPIComplete: 'readonly',
        test_timeline_wrappersRejectNullToken: 'readonly',
        test_webapp_diagnoseWebAppExists: 'readonly',
        test_webapp_diagnoseWebAppRunsClean: 'readonly',
        test_webapp_doGetExists: 'readonly',
        test_webapp_doGetWebDashboardExists: 'readonly',
        test_webapp_getWebAppUrlExists: 'readonly',
        test_webapp_getWebAppUrlReturnsString: 'readonly',
        test_webapp_includeHelperExists: 'readonly',
        test_webapp_orgChartHtmlExists: 'readonly',
        test_webapp_orgChartHtmlReturnsContent: 'readonly',
        test_webapp_pomsReferenceHtmlExists: 'readonly',
        test_webapp_pomsReferenceHtmlReturnsContent: 'readonly',
        test_webapp_sanitizeConfigExists: 'readonly',
        test_webapp_sanitizeConfigStripsInternal: 'readonly',
        test_webapp_serveFatalErrorExists: 'readonly',
        test_weeklyq_autoSelectExists: 'readonly',
        test_weeklyq_getPollFrequencyCallable: 'readonly',
        test_weeklyq_getPoolCountCallable: 'readonly',
        test_weeklyq_globalWrappersExist: 'readonly',
        test_weeklyq_moduleExists: 'readonly',
        test_weeklyq_publicAPIComplete: 'readonly',
        test_weeklyq_qColsExposed: 'readonly',
        test_weeklyq_wrappersRejectNullToken: 'readonly',
        test_workload_categoryLabelsExposed: 'readonly',
        test_workload_getSubCategoriesCallable: 'readonly',
        test_workload_globalWrappersExist: 'readonly',
        test_workload_moduleExists: 'readonly',
        test_workload_publicAPIComplete: 'readonly',
        test_workload_subCategoriesExposed: 'readonly',
        test_workload_triggerHandlersExist: 'readonly',
        test_workload_wrappersRejectNullToken: 'readonly',

        // Misc cross-file
        BACKFILL_MINUTES_DRIVE_DOCS: 'readonly',
        doGet: 'readonly',
        computeAuditRowHash_: 'readonly',
        getOrCreateMinutesSheet: 'readonly',
        getVersionHistory_: 'readonly'
      }
    },

    rules: {
      // ==========================================
      // ENABLED RULES (Important for code quality)
      // ==========================================

      // Catch critical errors
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty-pattern': 'error',
      'no-func-assign': 'error',
      'no-import-assign': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-template-curly-in-string': 'warn',
      'no-unreachable': 'warn',
      'no-unsafe-finally': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'warn',

      // Security-related
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-with': 'error',

      // ==========================================
      // DISABLED RULES (For legacy compatibility)
      // ==========================================

      // These are disabled to allow existing code to pass
      // Enable gradually as code is cleaned up
      'no-undef': 'error',
      'no-unused-vars': ['warn', { args: 'none', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_', vars: 'local' }],
      'no-redeclare': ['error', { builtinGlobals: false }],
      'no-empty': 'off',
      // CODE-05: Upgraded from 'warn' — loose equality (==) causes subtle type coercion bugs
      'eqeqeq': ['error', 'smart'],
      'semi': 'off',
      'quotes': 'off',
      'indent': 'off',
      'comma-dangle': 'off',
      'no-trailing-spaces': 'off',
      'eol-last': 'off',
      'max-len': 'off',
      'no-extra-semi': 'off',
      'strict': 'off',
      'no-var': 'off',
      'prefer-const': 'off',
      'no-useless-escape': 'off',
      'no-inner-declarations': 'off',
      'no-case-declarations': 'off',
      'no-prototype-builtins': 'warn',
      'getter-return': 'error',
      'no-constant-condition': 'off',
      'no-control-regex': 'off',
      'no-debugger': 'error',
      'no-dupe-args': 'error',
      'no-dupe-else-if': 'off',
      'no-empty-character-class': 'off',
      'no-ex-assign': 'off',
      'no-extra-boolean-cast': 'off',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'off',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'off',
      'no-obj-calls': 'off',
      'no-regex-spaces': 'off',
      'no-setter-return': 'off',
      'no-sparse-arrays': 'off',
      'no-unexpected-multiline': 'off',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'require-yield': 'off'
    }
  },

  // Ignore patterns
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'build.js',
      '*.config.js'
    ]
  }
];
